---

# tasks file for install pip on centos

- name: "centos | install epel repository"
  yum: name=epel-release state=present
  sudo: yes

- name: "centos | install python-pip"
  yum: name=python-pip state=present enablerepo=epel
  sudo: yes

