---

# tasks file for install pip on centos

- name: "install epel repository"
  yum: name=epel-release state=present
  become: true

- name: "centos | install python-pip"
  yum: name=python-pip state=present enablerepo=epel
  become: true
