---
# tasks file for ansible-pip

- name: install pip on CentOS
  include: centos.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS"

- name: install pip on Ubuntu
  include: ubuntu.yml
  when: ansible_os_family == "Debian"


- name: "make sure ~/.pip directory exists"
  file: path=~/.pip state=directory

- name: "config pip with pip.conf"
  template: src=pip.conf.j2 dest=~/.pip/pip.conf



